"""Per-query failure analysis — exposes which queries our retriever gets
wrong and WHY (rank of expected, top-5 reasoning, score deltas).

Usage:
    python -m scripts.failure_analysis                      # both eval sets
    python -m scripts.failure_analysis --set bootstrap      # one set
    python -m scripts.failure_analysis --threshold 3        # only show miss@K=3

Output: a markdown report at docs/failure_analysis.md plus stdout summary.
"""
from __future__ import annotations

import argparse
import json
import re
import time
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

from src.offline_guard import enforce_offline_if_cached  # noqa: E402

enforce_offline_if_cached()

from src.retrieval.retriever import Retriever  # noqa: E402

EVAL_SETS = {
    "public":    Path("datasets/public_test_set.json"),
    "bootstrap": Path("data/bootstrap_test_set.json"),
}


def normalize(s: str) -> str:
    return re.sub(r"\s+", "", s).lower()


def analyse(retriever: Retriever, queries: list[dict], set_name: str) -> dict:
    """For each query: where did the expected standard rank? What were the
    top-5 actually returned, and what scores led to that ordering?"""
    out_rows = []
    misses_at_3 = 0
    misses_at_5 = 0
    rank_distribution: dict[int, int] = {}  # rank -> count (0 = not in top-25)

    for q in queries:
        qid = q["id"]
        query = q["query"]
        expected_norm = {normalize(s) for s in q.get("expected_standards", [])}

        t0 = time.perf_counter()
        hits = retriever.search(query)
        latency = time.perf_counter() - t0

        # find expected rank
        expected_rank: int | None = None
        for h in hits:
            if normalize(h.is_code) in expected_norm:
                expected_rank = h.rank
                break
        if expected_rank is None:
            rank_distribution[0] = rank_distribution.get(0, 0) + 1
        else:
            rank_distribution[expected_rank] = rank_distribution.get(expected_rank, 0) + 1

        is_miss_at_3 = expected_rank is None or expected_rank > 3
        is_miss_at_5 = expected_rank is None or expected_rank > 5
        if is_miss_at_3: misses_at_3 += 1
        if is_miss_at_5: misses_at_5 += 1

        out_rows.append({
            "id": qid,
            "query": query,
            "expected": q.get("expected_standards", []),
            "expected_rank": expected_rank,
            "miss@3": is_miss_at_3,
            "miss@5": is_miss_at_5,
            "latency_s": round(latency, 3),
            "top5": [
                {
                    "rank": h.rank,
                    "is_code": h.is_code,
                    "title": h.title,
                    "rerank_score": round(h.rerank_score, 4),
                    "rrf_score": round(h.rrf_score, 4),
                    "category_boost": round(h.category_boost, 3),
                    "categories": list(h.categories),
                }
                for h in hits[:5]
            ],
        })

    return {
        "set": set_name,
        "n": len(queries),
        "misses_at_3": misses_at_3,
        "misses_at_5": misses_at_5,
        "rank_distribution": rank_distribution,
        "rows": out_rows,
    }


def write_markdown(reports: list[dict], out_path: Path):
    lines = ["# Per-query failure analysis\n"]
    lines.append(
        "Generated by `python -m scripts.failure_analysis`. For each query, "
        "shows the rank at which the expected standard appeared (or `—` if "
        "outside top-5), and the top-5 actually returned.\n"
    )
    for rep in reports:
        lines.append(f"\n## {rep['set']} test set ({rep['n']} queries)\n")
        lines.append(f"- Misses @3: **{rep['misses_at_3']} / {rep['n']}**  "
                     f"({100 * rep['misses_at_3'] / rep['n']:.1f}%)")
        lines.append(f"- Misses @5: **{rep['misses_at_5']} / {rep['n']}**  "
                     f"({100 * rep['misses_at_5'] / rep['n']:.1f}%)")
        # Rank distribution
        dist = rep["rank_distribution"]
        rd_parts = []
        for k in sorted(dist.keys()):
            label = f"rank {k}" if k > 0 else "not-in-top-25"
            rd_parts.append(f"`{label}={dist[k]}`")
        lines.append(f"- Rank distribution of expected codes: {' '.join(rd_parts)}")

        # Misses
        lines.append(f"\n### Misses (expected rank > 3)\n")
        any_miss = False
        for row in rep["rows"]:
            if not row["miss@3"]:
                continue
            any_miss = True
            lines.append(f"\n#### {row['id']} · expected `{row['expected'][0]}` "
                         f"· got rank {row['expected_rank'] or 'NOT FOUND'}")
            lines.append(f"> {row['query']}\n")
            lines.append("| Rank | Code | Title | rerank | rrf | cat-boost |")
            lines.append("|---:|---|---|---:|---:|---:|")
            for h in row["top5"]:
                marker = "✓" if normalize(h["is_code"]) in {normalize(c) for c in row["expected"]} else ""
                lines.append(
                    f"| {h['rank']} | `{h['is_code']}`{marker} | {h['title'][:50]} | "
                    f"{h['rerank_score']:.3f} | {h['rrf_score']:.3f} | {h['category_boost']:.2f} |"
                )
        if not any_miss:
            lines.append("_No misses on this set._")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--set", choices=["public", "bootstrap", "both"], default="both")
    ap.add_argument("--out", type=Path, default=Path("docs/failure_analysis.md"))
    args = ap.parse_args()

    retriever = Retriever()
    reports = []
    for name, path in EVAL_SETS.items():
        if args.set != "both" and name != args.set:
            continue
        if not path.exists():
            print(f"Skipping {name}: {path} not found")
            continue
        with path.open(encoding="utf-8") as f:
            queries = json.load(f)
        rep = analyse(retriever, queries, name)
        reports.append(rep)
        print(f"\n{name}: misses@3 = {rep['misses_at_3']}/{rep['n']}, "
              f"misses@5 = {rep['misses_at_5']}/{rep['n']}")

    if reports:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        write_markdown(reports, args.out)
        # also dump JSON for programmatic use
        json_path = args.out.with_suffix(".json")
        json_path.write_text(json.dumps(reports, ensure_ascii=False, indent=2),
                             encoding="utf-8")
        print(f"Wrote {json_path}")


if __name__ == "__main__":
    main()
